export const items = (queryInfo, arrSource, topDataInfo) => {
  return [
    {
      label: '部门名称',
      key: 'deptName',
      widget: 'input',
      initialValue: queryInfo?.deptName,
      required: true,
      span: '12',
      placeholder: '请输入部门名称',
      rules: [{ required: true, message: '请输入部门名称' }],
    },
    {
      label: '排序',
      key: 'orderNum',
      widget: 'input',
      initialValue: queryInfo?.orderNum,
      required: true,
      span: '12',
      placeholder: '请输入排序',
      rules: [{ required: true, message: '请输入排序' }],
    },
    {
      label: '负责人',
      key: 'leader',
      widget: 'input',
      initialValue: queryInfo?.leader,
      required: true,
      span: '12',
      placeholder: '请输入负责人',
      rules: [{ required: true, message: '请输入负责人' }],
    },
    {
      label: '联系电话',
      key: 'phone',
      widget: 'input',
      initialValue: queryInfo?.phone,
      required: true,
      span: '12',
      placeholder: '请输入联系电话',
      rules: [{ required: true, message: '请输入联系电话' }],
    },
    {
      label: '邮箱',
      key: 'email',
      widget: 'input',
      initialValue: queryInfo?.email,
      required: true,
      span: '12',
      placeholder: '请输入邮箱',
      rules: [{ required: true, message: '请输入邮箱' }],
    },
    {
      label: '部门状态',
      key: 'status',
      widget: 'select',
      option: [
        { label: '正常', value: '1' },
        { label: '停用', value: '2' },
      ],
      initialValue: queryInfo?.status,
      required: true,
      span: '12',
      placeholder: '请输入部门状态',
      rules: [{ required: true, message: '请输入部门状态' }],
    },
    {
      label: '上级菜单',
      key: 'parentId',
      widget: 'searchTree',
      span: '24',
      readSpan: 3,
      widgetProps: {
        allowClear: true,
        // onSearch: (searchValue) => console.log('SearchTreeOption', searchValue),
        // onChange: (selectd, selectedAll, isChecked) =>
        //   console.log('SearchTree-> onChange', selectd, selectedAll, isChecked),
      },
      initialValue: [topDataInfo],
      multiple: false,
      option: arrSource,
    },
  ]
}
