export const items = (queryInfo) => [
  // userId
  {
    label: '岗位名称',
    key: 'postName',
    widget: 'input',
    placeholder: '请输入岗位名称',
    initialValue: queryInfo?.postName,
    span: '24',
    required: true,
  },
  {
    label: '岗位编码',
    key: 'postCode',
    placeholder: '请输入岗位编码',
    widget: 'input',
    initialValue: queryInfo?.postCode,
    span: '24',
    required: true,
  },
  {
    label: '岗位顺序',
    key: 'postSort',
    placeholder: '请输入岗位顺序',
    widget: 'input',
    initialValue: queryInfo?.postSort,
    span: '24',
    required: true,
  },
  {
    label: '岗位状态',
    key: 'status',
    widget: 'select',
    option: [
      { label: '正常', value: '0' },
      { label: '停用', value: '1' },
    ],
    initialValue: queryInfo?.status,
    span: '24',
    required: true,
  },
  {
    label: '备注',
    key: 'remark',
    placeholder: '请输入备注',
    widget: 'textarea',
    initialValue: queryInfo?.remark,
    span: '24',
  },
]
