export const items = (queryInfo, drawerType) => [
  {
    label: '团队名',
    key: 'teamName',
    widget: 'input',
    initialValue: queryInfo?.teamName,
    widgetProps: {},
    required: true,
    placeholder: '输入团队名',
    rules: [{ required: true, message: '输入团队名' }],
    span: '12',
  },
  {
    label: '团队用户列表',
    key: 'teamUserList',
    widget: 'input',
    initialValue: queryInfo?.teamUserList,
    widgetProps: {},
    required: true,
    placeholder: '选择团队用户列表',
    rules: [{ required: true, message: '选择团队用户列表' }],
    span: '12',
  },
  {
    label: '团队描述',
    key: 'teamUserNameSplice',
    widget: 'input',
    initialValue: queryInfo?.teamUserNameSplice,
    widgetProps: {},
    required: true,
    placeholder: '团队描述',
    rules: [{ required: true, message: '团队描述' }],
    span: '12',
  },
  {
    label: '创建时间',
    key: 'createTime',
    widget: 'input',
    initialValue: queryInfo?.createTime,
    widgetProps: {},
    required: true,
    placeholder: '选择创建时间',
    hide: drawerType !== 'view',
    readSpan: 1,
  },
  {
    label: '更新时间',
    key: 'updateTime',
    widget: 'input',
    initialValue: queryInfo?.updateTime,
    widgetProps: {},
    required: true,
    placeholder: '选择更新时间',
    hide: drawerType !== 'view',
    readSpan: 1,
  },
]
