export const item = (seachValue) => [
  {
    label: '项目名称:',
    key: 'name',
    widget: 'input',
    initialValue: seachValue.name,
    widgetProps: {},
    placeholder: '请输入项目名称',
    span: '24',
    required: true,
    rules: [{ required: true, message: '请输入项目名称' }],
  },
  {
    label: '项目负责人:',
    key: 'projectLeaderName',
    widget: 'select',
    option: [
      { value: 1, label: '苹果' },
      { value: 2, label: '西瓜' },
      { value: 3, label: '香蕉' },
      { value: 4, label: '东北大冻梨' },
    ],
    initialValue: seachValue.projectLeaderName,
    widgetProps: {},
    span: '24',
    required: true,
    rules: [{ required: true, message: '请输入项目负责人' }],
  },
  {
    label: '起止日期:',
    key: 'begin',
    initialValue: seachValue.begin,
    widget: 'dateInput',
    widgetProps: {
      format: 'YYYY-MM-DD HH:mm:ss',
    },
    span: '24',
    required: true,
    rules: [{ required: true, message: '请输入起止日期' }],
  },
  {
    label: '截止日期:',
    key: 'end',
    initialValue: seachValue.end,
    widget: 'dateInput',
    widgetProps: {
      format: 'YYYY-MM-DD HH:mm:ss',
    },
    span: '24',
    required: true,
    rules: [{ required: true, message: '请输入截止日期' }],
  },
  {
    label: '项目描述:',
    key: 'descr',
    widget: 'textarea',
    initialValue: seachValue.descr,
    widgetProps: {},
    span: '24',
  },
]
