module.exports.milestonesSave = function (req, res) {
  return res
    .status(200)
    .json({ success: true, code: 200, message: '成功', data: '保存成功' })
}

module.exports.update = function (req, res) {
  return res.status(200).json({
    code: 200,
    message: '编辑成功',
    data: {},
  })
}

module.exports.selectPage = function (req, res) {
  return res.status(200).json({
    success: true,
    code: 200,
    message: '成功',
    data: {
      total: 4,
      list: [
        {
          milestonesId: 99,
          milestonesTitle: '长长长',
          startTime: '2022-04-06',
          dueTime: '2022-04-30',
          milestonesStatus: 2,
          degreeCompletion: 1.0,
          milestonesDesc: '长\n\n长\n\n长\n\n长\n\n长',
          projectId: 1320,
          createId: 69,
          createName: '邢跃锋',
          createTime: '2022-04-30 00:00:00',
          updateId: 69,
          updateName: '邢跃锋',
          updateTime: '2022-04-25 00:14:51',
          participateUser: null,
          closeTaskNum: 2,
          allTaskNum: 2,
          overtime: 1,
          overtimeNum: 4,
        },
        {
          milestonesId: 114,
          milestonesTitle: '王龙飞大佬',
          startTime: '2022-04-06',
          dueTime: '2022-04-21',
          milestonesStatus: 2,
          degreeCompletion: 0.0,
          milestonesDesc: '王龙飞大佬\n王龙飞大佬\n王龙飞大佬\n王龙飞大佬',
          projectId: 1320,
          createId: 69,
          createName: '邢跃锋',
          createTime: '2022-04-21 15:51:18',
          updateId: 69,
          updateName: '邢跃锋',
          updateTime: '2022-04-24 01:29:58',
          participateUser: null,
          closeTaskNum: 0,
          allTaskNum: 0,
          overtime: 1,
          overtimeNum: 4,
        },
        {
          milestonesId: 34,
          milestonesTitle: '标题',
          startTime: null,
          dueTime: '2022-03-26',
          milestonesStatus: 2,
          degreeCompletion: 0.0,
          milestonesDesc:
            '里程碑描述\n里程碑描\n里程碑\n里程\n里\n里程\n里程碑\n里程碑描\n里程碑描述',
          projectId: 1320,
          createId: 46,
          createName: '黄来平',
          createTime: '2022-03-02 17:32:20',
          updateId: 46,
          updateName: '黄来平',
          updateTime: '2022-03-15 01:07:50',
          participateUser: null,
          closeTaskNum: 0,
          allTaskNum: 0,
          overtime: 1,
          overtimeNum: 4,
        },
        {
          milestonesId: 37,
          milestonesTitle: '测试111',
          startTime: null,
          dueTime: '2022-03-20',
          milestonesStatus: 2,
          degreeCompletion: 0.0,
          milestonesDesc: '测试111',
          projectId: 1320,
          createId: 46,
          createName: '黄来平',
          createTime: '2022-03-02 00:48:54',
          updateId: 46,
          updateName: '黄来平',
          updateTime: '2022-04-02 18:01:20',
          participateUser: null,
          closeTaskNum: 0,
          allTaskNum: 0,
          overtime: 1,
          overtimeNum: 4,
        },
      ],
      pageNum: 1,
      pageSize: 10,
      size: 4,
      startRow: 1,
      endRow: 4,
      pages: 1,
      prePage: 0,
      nextPage: 0,
      isFirstPage: true,
      isLastPage: true,
      hasPreviousPage: false,
      hasNextPage: false,
      navigatePages: 8,
      navigatepageNums: [1],
      navigateFirstPage: 1,
      navigateLastPage: 1,
    },
  })
}
