module.exports.authList = [
  '/TodoList',
  '/tableList',
  '/home',
  '/demo',
  '/dom',
  '/dom/*',
  '/dom/milestone',
  '/milestone',
  '/milestone/*',
  '/*',
  '/project',
  '/project/*',
  '/exceptions',
  '/exceptions/403',
  '/exceptions/404',
  '/exceptions/500',
]
